In [31]:
from google.colab import files
uploaded = files.upload()

Saving AAPL.csv to AAPL (1).csv

In [32]:
import pandas as pd
import numpy as np

In [33]:
data = pd.read_csv("AAPL.csv")

In [34]:
df = pd.DataFrame(data)

In [35]:
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [36]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10409 entries, 0 to 10408
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10409 non-null  object
 1   Open       10409 non-null  float64
 2   High       10409 non-null  float64
 3   Low        10409 non-null  float64
 4   Close      10409 non-null  float64
 5   Adj Close  10409 non-null  float64
 6   Volume     10409 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 569.4+ KB

In [38]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,10409.000000,10409.000000,10409.000000,10409.000000,10409.000000,1.040900e+04
mean,13.959910,14.111936,13.809163,13.966757,13.350337,3.321778e+08
std,30.169244,30.514878,29.835055,30.191696,29.911132,3.393344e+08
min,0.049665,0.049665,0.049107,0.049107,0.038384,0.000000e+00
25%,0.281964,0.287946,0.274554,0.281250,0.234799,1.247604e+08
50%,0.468750,0.477679,0.459821,0.468750,0.386853,2.199680e+08
75%,14.217857,14.364286,14.043571,14.206071,12.188149,4.126108e+08
max,182.630005,182.940002,179.119995,182.009995,181.778397,7.421641e+09

In [39]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [40]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [41]:
df.dropna()

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [42]:
df.drop_duplicates()

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600
...,...,...,...,...,...,...,...
10404,2022-03-18,160.509995,164.479996,159.759995,163.979996,163.979996,123351200
10405,2022-03-21,163.509995,166.350006,163.009995,165.380005,165.380005,95811400
10406,2022-03-22,165.509995,169.419998,164.910004,168.820007,168.820007,81532000
10407,2022-03-23,167.990005,172.639999,167.649994,170.210007,170.210007,98062700
10408,2022-03-24,171.059998,174.139999,170.210007,174.070007,174.070007,90018700

In [46]:
average_open = df['Open'].mean()
print(average_open)

13.959909858007494

In [47]:
average_close = df['Close'].mean()
print(average_close)

13.966756942837927

In [48]:
maximum_high = df['High'].max()
print(maximum_high)

182.940002

In [49]:
minimum_low = df['Low'].min()
print(minimum_low)

0.049107

In [58]:
df['Daily_Delta'] = df['Close'] - df['Open']

In [59]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta,Daily_Return
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000,0.000000
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558,-0.456591
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558,-0.492580
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000,0.000000
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000,0.000000

In [60]:
df['Daily_Delta'].sort_index()

0        0.000000
1       -0.000558
2       -0.000558
3        0.000000
4        0.000000
           ...
10404    3.470001
10405    1.870010
10406    3.310012
10407    2.220002
10408    3.010009
Name: Daily_Delta, Length: 10409, dtype: float64

In [62]:
df['Daily_Return'] = (df['Daily_Delta'] /df['Open']) * 100

In [63]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta,Daily_Return
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000,0.000000
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558,-0.456591
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558,-0.492580
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000,0.000000
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000,0.000000

In [64]:
df['Daily_Return'].sort_index()

0        0.000000
1       -0.456591
2       -0.492580
3        0.000000
4        0.000000
           ...
10404    2.161860
10405    1.143667
10406    1.999886
10407    1.321508
10408    1.759622
Name: Daily_Return, Length: 10409, dtype: float64

In [65]:
Average_volume = df['Volume'].mean()
Max_volume = df['Volume'].max()
Min_volume = df['Volume'].min()
print(Average_volume)
print(Max_volume)
print(Min_volume)

332177847.17071766
7421640800
0